language: php

php:
  - 5.6
  - 7
  - hhvm

sudo: false

install:
  - composer selfupdate
  - composer install

script:
  - composer test

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/coveralls -v; fi

addons:
  code_climate:
    repo_token: e4ad328487f600d7487603cd905e1575ccb0055b9ea27b142643568e9e82a608
